<?php
/*
 * @category    Spotii
 * @package     Spotii_Spotiipay
 * @copyright   Copyright (c) Spotii (https://www.spotii.me/)
 */
?>
<script type="text/x-magento-init">
var flag = false;
console.log(flag);
if(flag){
    {
        "*": {
            "productWidget": {
                "jsConfig" : <?php echo json_encode($this->getJsConfig()) ?>
            }
        }
    }
}else{console.log("not rendered");}
</script>
