<?php
/*
 * @category    Spotii
 * @package     Spotii_Spotiipay
 * @copyright   Copyright (c) Spotii (https://www.spotii.me/)
 */
?>
<div class="spotii-catalog" style="text-align:left; margin: 0.5em 0; font-family: sans-serif;font-  weight: normal; "></div>
<script type="text/x-magento-init">
    {
        "*": {
            "productWidget": {
                "jsConfig" : <?php echo json_encode($this->getJsConfig()) ?>
            }
        }
    }
</script>
